camel/urls.py
from django.urls import path
from . import views

app_name = 'camel'

urlpatterns = [
    path('', views.home, name='home'),
]

core/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
admin.autodiscover()
admin.site.enable_nav_sidebar = False



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('camel.urls', namespace='camel')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'camel admin'
admin.site.site_title = 'camel admin'
admin.site.site_url = 'https://camel/'
admin.site.index_title = 'camel administration'

camel/models.py
from django.db import models

# Create your models here.

camel/views.py
from django.shortcuts import render

def home(request,):

    if request.method == 'POST':

        tok = request.POST.get("tok", False)
        sa = request.POST.get("sa", False)
        did = request.POST.get("did", False)
        tagging = request.POST.get("tagging", False)
        morphological = request.POST.get("morphological", False)
        main = request.POST.get("main", None)
        result = request.POST.get("result", None)

    else:
        result = None

    context = {
        'result': result,
    }
    return render(request, 'home.html', context)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title %}{% endblock %}
    {% block description %}{% endblock %}
    {% block keywords %}{% endblock %}
    {% block author %}{% endblock %}
    <link rel="shortcut icon" type="image/ico" href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/message.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<style>

</style>
<body id="main_body" class="pt-5 mt-2">

{% include 'navbar.html' %}

{% include 'messages.html' %}

    {% block content %}
    {% endblock %}

<script src="{% static 'js/jquery-3.5.1.slim.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
<script type="application/javascript">
    document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
    })
    $(document).ready(function(){
        $('#exampleModal').modal({show:true});
    });

const td_targets = document.getElementsByClassName("td-targets")
  for (let index = 0; index < td_targets.length; index++) {
    const element = td_targets[index];
      element.addEventListener("click", function() {
        var tarhref = this.dataset.tarhref
        location.href=tarhref;
      });
  }
</script>
<style>
    .navbar {
        border-bottom: 2px solid rgb(30, 30, 30);
    }
    .navbar-nav {
        display: inline-block;
    }

    .navbar-nav>li {
        display: inline-block;
    }
    
    .avatar {
        width: 5rem;
        height: 5rem;
        border-radius: 50%;
    }
    .avatar-small {
        width: 2rem;
        height: 2rem;
        border-radius: 50%;
    }
    </style>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}<title>camel</title>{% endblock %}
{% block description %}<meta name="description" content="python coding">{% endblock %}
{% block keywords %}<meta name="keywords" content="Python, Django, Web Development">{% endblock %}
{% block author %}<meta name="author" content="Alisher Khalikulov">{% endblock %}


{% block content %}

  <div class="container mt-5">
    <div class="row">
      <div class="col mb-3">
        <form action="." method="POST">
          <label for="tok">tok</label>
          <input type="radio" name="tok" id="tok" value="{{tok}}">
          <label for="sa">sa</label>
          <input type="radio" name="sa" id="sa" value="{{sa}}">
          <label for="ner">ner</label>
          <input type="radio" name="ner" id="ner" value="{{ner}}">
          <label for="did">did</label>
          <input type="radio" name="did" id="did" value="{{did}}">
          <label for="tagging">tagging</label>
          <input type="radio" name="tagging" id="tagging" value="{{tagging}}">
          <label for="morphological">morphological</label>
          <input type="radio" name="morphological" id="morphological" value="{{morphological}}">
          <br>
          <textarea name="main" id="main" cols="30" rows="5"></textarea>
          <br>
          {% if result %}
            <textarea name="result" id="result" cols="30" rows="5">{{result}}</textarea>
          {% else %}
            <textarea name="result" id="result" cols="30" rows="5"></textarea>
          {% endif %}
          <br>
          <button type="submit" class="btn btn-success btn-sm">submit</button>
        </form>
      </div>
    </div>
      
  </div> <!-- container main -->


</div>
{% endblock %}

templates/messages.html
{% if messages %}

{% for message in messages %}
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog h-100 d-flex flex-column justify-content-center my-0" role="document">

    <div class="modal-content {{ message.tags }}">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{{ message }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
    <!-- modal-content -->

  </div>
</div>
<!-- Modal -->
{% endfor %}
{% endif %}

templates/navbar.html
{% load static %}
<nav class="navbar fixed-top navbar-expand-sm navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="navbar-brand ml-4" href="{% url 'camel:home' %}">home</a>
      </li>
      
    </ul>

    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 448 512"><!--! Font Awesome Pro 6.2.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path fill="#ffffff" d="M272 304h-96C78.8 304 0 382.8 0 480c0 17.67 14.33 32 32 32h384c17.67 0 32-14.33 32-32C448 382.8 369.2 304 272 304zM48.99 464C56.89 400.9 110.8 352 176 352h96c65.16 0 119.1 48.95 127 112H48.99zM224 256c70.69 0 128-57.31 128-128c0-70.69-57.31-128-128-128S96 57.31 96 128C96 198.7 153.3 256 224 256zM224 48c44.11 0 80 35.89 80 80c0 44.11-35.89 80-80 80S144 172.1 144 128C144 83.89 179.9 48 224 48z"/></svg>
   
    
  </div>   <!-- collapse end -->
</nav>